config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :communities do
    namespace :communities do
      resources :posts do
        resources :comments
      end
    end
  end

  resources :posts, only: [:new, :create, :show, :destroy] do
    resources :likes, only: [:create, :update, :destroy] 
  end

  root to: 'communities#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/community.rb
class Community < ApplicationRecord
  has_many :posts, dependent: :destroy
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :community
  has_many :comments, dependent: :destroy
  belongs_to :user
  has_many :likes, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :communities
  has_many :comments
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:index, :show]
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/communities/comments_controller.rb
module Communities
  class CommentsController < ApplicationController
    def new
      @comment = Comment.new
    end
  
    def create
      @post = Post.find(params[:post_id])
  
      @comment = @post.comments.create(params[:comment].permit(:body))
      @comment.user = current_user
      @comment.save
  
      redirect_to community_communities_post_path(@post.community, @post)
    end
  
    def show
      @comment = Comment.find(params[:id])
    end
  
    def destroy
      @post = Post.find(params[:post_id])
      @comment = @post.comments.find(params[:id])
      @comment.destroy
      redirect_to community_communities_post_path(@post.community, @post)
    end
  end  
end

app/controllers/communities/posts_controller.rb
module Communities
  class PostsController < ApplicationController
    def create
      @community = Community.find(params[:community_id])
  
      @post = @community.posts.create(params[:post].permit(:title, :content))
      @post.user = current_user
      @post.save
  
      redirect_to community_path(@community)
    end
  
    def show
      @post = Post.find(params[:id])
    end
  
    def destroy
      @community = Community.find(params[:community_id])
      @post = @community.posts.find(params[:id])
      @post.destroy
      redirect_to community_post_path(@post.community, @post)
    end

  end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_community, only: [:show, :edit, :update, :destroy]

  # GET /communities
  # GET /communities.json
  def index
    @communities = Community.all
  end

  # GET /communities/1
  # GET /communities/1.json
  def show
  end

  # GET /communities/new
  def new
    @community = current_user.communities.build
  end

  # GET /communities/1/edit
  def edit
  end

  # POST /communities
  # POST /communities.json
  def create
    @community = current_user.communities.build(community_params)

    respond_to do |format|
      if @community.save
        format.html { redirect_to @community, notice: 'Community was successfully created.' }
        format.json { render :show, status: :created, location: @community }
      else
        format.html { render :new }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/1
  # PATCH/PUT /communities/1.json
  def update
    respond_to do |format|
      if @community.update(community_params)
        format.html { redirect_to @community, notice: 'Community was successfully updated.' }
        format.json { render :show, status: :ok, location: @community }
      else
        format.html { render :edit }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/1
  # DELETE /communities/1.json
  def destroy
    @community.destroy
    respond_to do |format|
      format.html { redirect_to communities_url, notice: 'Community was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community
      @community = Community.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def community_params
      params.require(:community).permit(:name, :description)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post
  before_action :find_like, only: [:destroy]
  
  def create
    if already_liked?
      flash[:notice] = "You can't like more than once"
    else
      @post.likes.create(user_id: current_user.id)
    end
    redirect_to post_path(@post)
  end

  def destroy
    if !(already_liked?)
      flash[:notice] = "Cannot unlike"
    else
      @like.destroy
    end
    redirect_to post_path(@post)
  end

  def find_like
    @like = @post.likes.find(params[:id])
 end

  private
  def find_post
    @post = Post.find(params[:post_id])
  end

  def already_liked?
    Like.where(user_id: current_user.id, post_id:
    params[:post_id]).exists?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params.merge(user: current_user))
    if @post.save
      redirect_to community_communities_post_path(@post.community, @post)
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to communities_url, notice: 'Community was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :community_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_for([@post.community, @post, @post.comments.build]) do |f| %>

<p>
  <%= f.label :body %>
  <%= f.text_area :body %>
</p>
<br>
<p>
  <%= f.submit %>
</p>

<% end %>

app/views/communities/_form.html.erb
<%= form_with(model: community, local: true) do |form| %>
  <% if community.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(community.errors.count, "error") %> prohibited this community from being saved:</h2>

      <ul>
        <% community.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/communities/comments/_comment.html.erb
<p><%= comment.body %></p>
<p><%= time_ago_in_words(comment.created_at) %></p>

<p> <%= link_to 'Delete', community_communities_post_comment_path(comment.post.community, comment.post, comment), method: :delete, data: { confirm: 'Are you sure?'} %> </p>

app/views/communities/comments/_form.html.erb
<%= form_for([@post.community, :communities, @post, @post.comments.build]) do |f| %>

<p>
  <%= f.label :body %>
  <%= f.text_area :body %>
</p>
<br>
<p>
  <%= f.submit %>
</p>

<% end %>

app/views/communities/edit.html.erb
<h1>Editing Community</h1>

<%= render 'form', community: @community %>

<%= link_to 'Show', @community %> |
<%= link_to 'Back', communities_path %>

app/views/communities/index.html.erb
<h1>Communities</h1>

<table>
  <div>
    <% @communities.each do |community| %>

      <div class="row">
        <div class="col-sm-12">
          <div class="card">
            <div class="card-body">

              <h5 class="card-title"><%= community.name %></h5>
              <p class="card-text"><%= community.description %></p>
              <%= link_to 'Show', community %>
              <%= link_to 'Edit', edit_community_path(community) %>
              <%= link_to 'Destroy', community, method: :delete, data: { confirm: 'Are you sure?' } %>

            </div>
          </div>
        </div>
      </div>

    <% end %>
  </div>
</table>

app/views/communities/new.html.erb
<h1>New Community</h1>

<%= render 'form', community: @community %>

<%= link_to 'Back', communities_path %>

app/views/communities/posts/_form.html.erb
<%= form_for([@community, :communities, @community.posts.build]) do |f|%>
<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :content %><br>
  <%= f.text_area :content %>
</p>
<br>
<p>
  <%= f.submit %>
</p>

<% end %>

app/views/communities/posts/_post.html.erb
<h4><%= post.title %> <br></h4>

<p><%= post.content%><p>

<%= link_to 'Show', community_communities_post_path(post.community, post)%>

app/views/communities/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<h3> <%= @post.comments.count %> Comments </h3>
     <%= render @post.comments %>
     <h3> Add a Comment: </h3>
     <%= render 'communities/comments/form' %>


<%= link_to 'Edit', edit_community_communities_post_path(@post.community, @post) %> |
<%= link_to 'Back', community_path(@post.community) %>

app/views/communities/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @community.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @community.description %>
</p>

<p>
  <strong>Created by: <%= current_user.nickname %></strong>
</p>

<p><%= pluralize(@community.posts.count, 'Post') %></p><br>
<% @community.posts.each do |post| %>
  <%= render 'communities/posts/post', post: post %>
  <%= link_to 'Edit', edit_community_path(@community) %>
  <%= link_to 'Back', communities_path %>
  <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </head>

  <body>
    
    <nav class="navbar navbar sticky-top navbar-expand-lg navbar-light" style="background-color:#e3f2fd;">
    <a class="navbar-brand" ><%= link_to 'DJreddit', communities_path %></a>
    <ul class ="navbar-nav mr-auto">   
      <div>
        <li class="nav-link" ><%= link_to 'New Community', new_community_path %></li>
      </div>
      
      <div>
        <li class="nav-link" ><%= link_to 'New Post', new_post_path %></li>
      </div>
    </ul>    
        <div class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" placeholder="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </div>
            <% if user_signed_in? %>
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" ><%= current_user.nickname%></a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            
            <a class="dropdown-item"> <%= link_to 'Edit profile', edit_user_registration_path %></a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item"> <%= link_to "Logout", destroy_user_session_path, method: :delete %></a>
            <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
            <% end %>
          </div>
        </div>
    </ul>
  </nav>

  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for([@community, @community.posts.build]) do |f|%>
<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :content %><br>
  <%= f.text_area :content %>
</p>
<br>
<p>
  <%= f.submit %>
</p>

<% end %>

app/views/posts/new.html.erb
<%= form_for([@post]) do |f|%>
<br>
<div>
  <%= f.label :community_id %>
  <%= f.collection_select :community_id, Community.all, :id, :name %>
</div>
<br>
<div class= "form-group">
  <%= f.label :title %><br>
  <%= f.text_field :title, class:"form-control" %>
</div>

<div class="form-group">
  <%= f.label :content %><br>
  <%= f.text_area :content, class:"form-control" %>
</div>
<br>
<div>
  <%= f.submit %>
</div>

<% end %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<h3> <%= @post.comments.count %> Comments </h3>
     <% @post.comments.each do |comment| %>
     <%= render 'communities/comments/comment', comment: comment %>
     <% end %>
     <h3> Add a Comment: </h3>
     <%= render 'communities/comments/form' %>

  <% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
  <% if pre_like %>
  <%= button_to 'Unlike', post_like_path(@post, pre_like), method: :delete %>
  <% else %>
  <%= button_to 'Like', post_likes_path(@post), method: :post %>
  <% end %>
  <p><%= @post.likes.count %> <%= (@post.likes.count) == 1 ? 'Like' : 'Likes'%></p>

<%= link_to 'Edit', edit_community_communities_post_path(@post.community, @post) %> |
<%= link_to 'Back', community_path(@post.community) %>